service: ahurynovich-cv

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

# you can overwrite defaults here
#  stage: dev

custom:
  client:
    bucketName: ahurynovich-cv-s3-bucket
    # [other configuration parameters]
    distributionFolder: dist/client
    indexDocument: index.html

plugins:
  - serverless-finch