version: 2.1
orbs:
  node: circleci/node@x.y
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~project/node_modules
          override-ci-command: npm install
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build
          command: npm run build
  deploy:
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "hello world"

workflows:
  version: 2.1
  test_and_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - hold


