version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  install-packages:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~project/node_modules
          override-ci-command: npm install
  test:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing
          command: npm run test
  build-clean:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Build Clean
          command: npm run build:clean
  build:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Building
          command: npm run build:client:prod
  deploy:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo "hello world"

workflows:
  version: 2.1
  test_and_build_and_deploy:
    jobs:
      - install-packages
      - test
          requires:
            - install-packages
      - build-clean
          requires:
            - install-packages
      - build:
          requires:
            - test
            - build-clean
      - hold:
          type: approval
          requires:
            - build
            - test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - hold


