version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
  codecov: codecov/codecov@3.2.3

executors:
  exec-docker-node:
    docker:
      - image: cimg/node:16.11.1

commands:
  cmd-save-cache:
    steps:
      - save_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  cmd-restore-cache:
    steps:
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}

jobs:
  install-packages:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Install packages"
          command: npm install
      - cmd-save-cache
  lint:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Linting"
          command: npm run lint
  test-unit-integration:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Testing (Unit and Integration Tests)"
          command: npm run test:ci
  test-unit-integration-with-reports:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Testing (Unit and Integration Tests) with reports"
          command: npm run test:ci:with:reports
      - store_artifacts:
          path: ./test-reports
      - store_test_results:
          path: ./test-reports/test-results
      - codecov/upload:
          file: ./test-reports/test-coverage/cobertura-coverage.xml
  test-sca:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Snyk Authentication"
          command: npm run sca:auth $SNYK_TOKEN
      - run:
          name: "Code Vulnerabilities Scan"
          command: npm run sca:test
  build-clean-app:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Cleaning previous Application Build"
          command: npm run build:clean
  build-app:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Building Application"
          command: npm run build:client:prod
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'
  deploy-app:
    executor: exec-docker-node
    steps:
      - aws-cli/setup:
          profile-name: AHurynovichCV_Profile
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - checkout
      - cmd-restore-cache
      - attach_workspace:
            at: .
      - run:
          name: "Deploying Application"
          command: npm run deploy:s3
  build-components-library:
    executor: exec-docker-node
    steps:
      - checkout
      - cmd-restore-cache
      - run:
          name: "Cleaning previous Components Library Build"
          command: npm run storybook:build:clean
      - run:
          name: "Building Components Library"
          command: npm run storybook:build
      - persist_to_workspace:
          root: .
          paths:
            - 'storybook-static'
  deploy-components-library:
    executor: exec-docker-node
    steps:
      - aws-cli/setup:
          profile-name: AHurynovichCV_Profile
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - checkout
      - cmd-restore-cache
      - attach_workspace:
            at: .
      - run:
          name: "Deploying Components Library"
          command: npm run storybook:deploy:s3

workflows:
  Common workflow:
    when:
      branches:
        ignore:
          - main
          - develop
    jobs:
      - install-packages:
      - lint:
          requires:
            - install-packages
      - test-unit-integration:
          requires:
            - install-packages
  Pre-commitment (develop) workflow:
    jobs:
      - install-packages:
          filters:
            branches:
              only:
                - develop
      - lint:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - develop
      - test-unit-integration:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - develop
      - build-clean-app:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - develop
      - build-app:
          requires:
            - lint
            - test-unit-integration
            - build-clean-app
          filters:
            branches:
              only:
                - develop
  Commitment (main) workflow:
    jobs:
      - install-packages:
          filters:
            branches:
              only:
                - main
      - lint:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - main
      - test-unit-integration-with-reports:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - main
      - test-sca:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - main
      - build-clean-app:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - main
      - build-app:
          requires:
            - lint
            - test-unit-integration-with-reports
            - test-sca
            - build-clean-app
          filters:
            branches:
              only:
                - main
      - hold-deploy-app:
          name: "[Approve App Deployment]"
          type: approval
          requires:
            - build-app
          filters:
            branches:
              only:
                - main
      - deploy-app:
          requires:
            - "[Approve App Deployment]"
          filters:
            branches:
              only:
                - main
      - hold-deploy-components-library:
          type: approval
          name: "[Approve Components Lib Deployment]"
          filters:
            branches:
              only:
                - main
      - build-components-library:
          requires:
            - "[Approve Components Lib Deployment]"
          filters:
            branches:
              only:
                - main
      - deploy-components-library:
          requires:
            - build-components-library
          filters:
            branches:
              only:
                - main
