version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  install-packages:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install packages
          command: npm install
      - save_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  lint-and-test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Testing (Unit Tests)
          command: npm run test:unit
  sca-test:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Snyk Authentication
          command: snyk auth SNYK_TOKEN
      - run:
          name: Code Vulnerabilities Scan
          command: npm run sca:test
  build-clean:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Build Clean
          command: npm run build-clean
  build:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - checkout
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Building
          command: npm run build:client:prod
      - persist_to_workspace:
          root: .
          paths:
            - 'dist'
  deploy:
    docker:
      - image: cimg/node:16.11.1
    steps:
      - aws-cli/setup:
          profile-name: AHurynovichCV_Profile
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - checkout
      - restore_cache:
          key: package-cache-{{ checksum "package-lock.json" }}
      - attach_workspace:
            at: .
      - run:
          name: Deploying
          command: npm run deploy:s3:nc

workflows:
  version: 2.1
  Common workflow:
    jobs:
      - install-packages:
          filters:
            branches:
              ignore:
                - main
                - develop
      - lint-and-test:
          requires:
            - install-packages
          filters:
            branches:
              ignore:
                - main
                - develop
      - sca-test:
          requires:
            - install-packages
          filters:
            branches:
              ignore:
                - main
                - develop
  Pre-commitment (develop) workflow:
    jobs:
      - install-packages:
          filters:
            branches:
              only:
                - develop
      - lint-and-test:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - develop
      - build-clean:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - develop
      - build:
          requires:
            - lint-and-test
            - build-clean
          filters:
            branches:
              only:
                - develop
  Commitment (main) workflow:
    jobs:
      - install-packages:
          filters:
            branches:
              only:
                - main
      - lint-and-test:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - main
      - build-clean:
          requires:
            - install-packages
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - lint-and-test
            - build-clean
          filters:
            branches:
              only:
                - main
      - hold:
          type: approval
          requires:
            - build
            - lint-and-test
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only:
                - main
