// [xsmall-max, small-min, small-max, medium-min, medium-max, large-min, large-max, xlarge-min, xlarge-max, xxlarge-min]
const ALLOWED_BREAKPOINTS_PX = [319, 320, 767, 768, 1023, 1024, 1365, 1366, 1919, 1920];
const VARIABLE_REGEX = [/\$.*/];
const ALLOWED_BREAKPOINTS_MIN_MAX_WIDTH = ALLOWED_BREAKPOINTS_PX.map((v) => `${v}px`).concat(VARIABLE_REGEX);

module.exports = {
    extends: ['stylelint-config-prettier', 'stylelint-config-standard-scss'],
    plugins: ['stylelint-scss', 'stylelint-order'],
    reportInvalidScopeDisables: true,
    reportNeedlessDisables: true,
    reportDescriptionlessDisables: true,
    rules: {
        'string-quotes': 'single',
        indentation: 4,
        'scss/at-mixin-argumentless-call-parentheses': 'never',
        'unit-allowed-list': ['px', '%', 'vh', 'vw', 'pt', 's', 'ms', 'deg', 'fr'],
        'unit-no-unknown': true,
        'declaration-no-important': true,
        'color-named': 'never',
        'length-zero-no-unit': true,
        'media-feature-name-value-allowed-list': [
            {
                'max-width': ALLOWED_BREAKPOINTS_MIN_MAX_WIDTH,
                'min-width': ALLOWED_BREAKPOINTS_MIN_MAX_WIDTH,
            },
            {
                message: [
                    '[media-feature-name-value-allowed-list]',
                    'Allowed for min-width/max-width:',
                    ALLOWED_BREAKPOINTS_MIN_MAX_WIDTH.join(', '),
                ].join('\n'),
            },
        ],
        'property-no-unknown': true,
        'no-duplicate-at-import-rules': true,
        'no-duplicate-selectors': true,
        'selector-type-no-unknown': true,
        'selector-pseudo-class-no-unknown': true,
        'selector-pseudo-element-no-unknown': true,
        'selector-max-compound-selectors': 5,
        'selector-max-id': [
            0,
            {
                message: [
                    '[selector-max-id]',
                    'Dont use id for styling elements.',
                    'Ids is hard to support and could be used only for JS/a11y reasons.',
                ],
            },
        ],
        'order/order': [
            [
                'custom-properties',
                'dollar-variables',
                {
                    type: 'at-rule',
                    name: 'extend',
                },
                {
                    type: 'at-rule',
                    name: 'include',
                    hasBlock: false,
                },
                'declarations',
                {
                    type: 'at-rule',
                    name: 'include',
                    hasBlock: true,
                },
                'rules',
            ],
        ],
        'order/properties-order': [
            [
                {
                    groupName: 'content',
                    properties: ['content'],
                },
                {
                    groupName: 'position',
                    properties: ['position', 'top', 'right', 'bottom', 'left', 'float', 'clear'],
                },
                {
                    groupName: 'layout',
                    properties: [
                        'display',
                        'z-index',
                        'table-layout',
                        'grid',
                        'grid-area',
                        'grid-auto-flow',
                        'grid-auto-rows',
                        'grid-auto-columns',
                        'grid-row',
                        'grid-row-start',
                        'grid-row-end',
                        'grid-column',
                        'grid-column-start',
                        'grid-column-end',
                        'grid-gap',
                        'grid-row-gap',
                        'grid-column-gap',
                        'grid-template',
                        'grid-template-areas',
                        'grid-template-rows',
                        'grid-template-columns',
                        'flex-flow',
                        'flex-direction',
                        'flex-wrap',
                        'justify-content',
                        'align-items',
                        'align-content',
                        'align-self',
                        'order',
                        'flex',
                        'flex-grow',
                        'flex-shrink',
                        'flex-basis',
                    ],
                },
                {
                    groupName: 'clipping',
                    properties: ['overflow', 'overflow-x', 'overflow-y', 'clip'],
                },
                {
                    groupName: 'dimension',
                    properties: ['width', 'min-width', 'max-width', 'height', 'min-height', 'max-height'],
                },
                {
                    groupName: 'boxModel',
                    properties: [
                        'margin',
                        'margin-top',
                        'margin-right',
                        'margin-bottom',
                        'margin-left',
                        'padding',
                        'padding-top',
                        'padding-right',
                        'padding-bottom',
                        'padding-left',
                        'box-sizing',
                        'border-radius',
                        'border-top-left-radius',
                        'border-top-right-radius',
                        'border-bottom-right-radius',
                        'border-bottom-left-radius',
                        'border-image',
                        'border-collapse',
                        'border-spacing',
                        'border',
                        'border-width',
                        'border-style',
                        'border-color',
                        'border-top',
                        'border-top-color',
                        'border-top-style',
                        'border-top-width',
                        'border-right',
                        'border-right-color',
                        'border-right-style',
                        'border-right-width',
                        'border-bottom',
                        'border-bottom-color',
                        'border-bottom-style',
                        'border-bottom-width',
                        'border-left',
                        'border-left-color',
                        'border-left-style',
                        'border-left-width',
                        'outline',
                        'outline-color',
                        'outline-offset',
                        'outline-style',
                        'outline-width',
                        'box-shadow',
                        'cursor',
                    ],
                },
                {
                    groupName: 'list',
                    properties: ['list-style', 'list-style-image', 'list-style-position', 'list-style-type'],
                },
                {
                    groupName: 'visibility',
                    properties: [
                        'opacity',
                        'visibility',
                        'zoom',
                        'transform',
                        'transform-origin',
                        'transform-style',
                    ],
                },
                {
                    groupName: 'background',
                    properties: [
                        'background',
                        'background-attachment',
                        'background-clip',
                        'background-color',
                        'background-image',
                        'background-origin',
                        'background-position',
                        'background-position-x',
                        'background-position-y',
                        'background-repeat',
                        'background-size',
                    ],
                },
                {
                    groupName: 'typography',
                    properties: [
                        'columns',
                        'column-count',
                        'column-gap',
                        'column-rule',
                        'column-width',
                        'direction',
                        'vertical-align',
                        'text-align',
                        'text-indent',
                        'text-decoration',
                        'text-decoration-color',
                        'text-decoration-line',
                        'text-decoration-style',
                        'text-overflow',
                        'text-shadow',
                        'text-transform',
                        'white-space',
                        'word-break',
                        'word-spacing',
                        'word-wrap',
                        'writing-mode',
                        'letter-spacing',
                        'color',
                        'font',
                        'font-family',
                        'font-size',
                        'font-stretch',
                        'font-style',
                        'font-variant',
                        'font-weight',
                        'line-height',
                    ],
                },
                {
                    groupName: 'animation',
                    properties: [
                        'transition',
                        'transition-delay',
                        'transition-property',
                        'transition-timing-function',
                        'animation',
                        'animation-delay',
                    ],
                },
            ],
            {
                unspecified: 'bottomAlphabetical', // Rest unspecified properties order rule
            },
        ],
    },
};
